name: Deploying on Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #       - uses: actions/checkout@v3
  #       - name: Use Node.js 14
  #         uses: actions/setup-node@v3
  #         with:
  #           node-version: 14
  #           cache: 'npm'

  #       - run: npm install
  #       - run: npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Generate SHA
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: Dockerfile
          push: true
          tags: |
            alekkdev/up-tsi-backend:latest
            alekkdev/up-tsi-backend:${{ steps.generate_sha.outputs.sha }}